//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaTuoiBaSanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public Nullable<double> GiaNhap { get; set; }
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string MaLoai { get; set; }
        public string MaDVT { get; set; }
        public string MaNCC { get; set; }
        public string MaKho { get; set; }
        public Nullable<double> DonGia1 { get; set; }
        public Nullable<double> DonGia2 { get; set; }
        public Nullable<double> DonGia3 { get; set; }
        public Nullable<double> DonGia4 { get; set; }
        public Nullable<double> GiaLe { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual LoaiHang LoaiHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual KhoHang KhoHang { get; set; }
    }
}
